### ISSUE TITLE
[Bug]: Build failure with mingw

### ISSUE THREAD

**Issue by star-hengxing** [facebookincubator/dispenso#30]
### What happened?

https://github.com/xmake-io/xmake-repo/actions/runs/8521965195/job/23341173486

I think using own namspace wrap system header is bad, even if other compilers don't build failure.

https://github.com/facebookincubator/dispenso/blob/670980ddc21e3482c86e821ca53a5f020bccca07/dispenso/detail/quanta.cpp#L10-L13

### Version

latest (Edge)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by graphicsMan** [comment]
Agreed, the namespace should not wrap the includes.  Are you interested in submitting a PR?  I should be able to get around to reviewing code and/or making the fix by the end of the week.  Please note that I don't currently have a mingw setup, so I may ask you for help testing or getting mingw set up.  Thanks!

**Comment by graphicsMan** [comment]
Thanks for the contribution @star-hengxing
